jobs:
- template: azure-pipelines.template.yml
  parameters:
    name: linux
    vmImage: 'ubuntu-16.04'

- template: azure-pipelines.template.yml
  parameters:
    name: windows
    vmImage: 'vs2017-win2016'

- template: azure-pipelines.template.yml
  parameters:
    name: macos
    vmImage: 'xcode9-macos10.13'

